//GET
export const GET_INSTRUCTORS = "GET_INSTRUCTORS";
export const GET_INSTRUCTORS_REQUEST = `${GET_INSTRUCTORS}_REQUEST`;
export const GET_INSTRUCTORS_SUCCESS = `${GET_INSTRUCTORS}_SUCCESS`;
export const GET_INSTRUCTORS_FAILURE = `${GET_INSTRUCTORS}_FAILURE`;

//ADD
export const ADD_INSTRUCTOR = "ADD_INSTRUCTOR";
export const ADD_INSTRUCTOR_REQUEST = `${ADD_INSTRUCTOR}_REQUEST`;
export const ADD_INSTRUCTOR_SUCCESS = `${ADD_INSTRUCTOR}_SUCCESS`;
export const ADD_INSTRUCTOR_FAILURE = `${ADD_INSTRUCTOR}_FAILURE`;

//DELETE
export const DELETE_INSTRUCTOR = "DELETE_INSTRUCTOR";
export const DELETE_INSTRUCTOR_REQUEST = `${DELETE_INSTRUCTOR}_REQUEST`;
export const DELETE_INSTRUCTOR_SUCCESS = `${DELETE_INSTRUCTOR}_SUCCESS`;
export const DELETE_INSTRUCTOR_FAILURE = `${DELETE_INSTRUCTOR}_FAILURE`;

//UPDATE
export const EDIT_INSTRUCTOR = "EDIT_INSTRUCTOR";
export const EDIT_INSTRUCTOR_REQUEST = `${EDIT_INSTRUCTOR}_REQUEST`;
export const EDIT_INSTRUCTOR_SUCCESS = `${EDIT_INSTRUCTOR}_SUCCESS`;
export const EDIT_INSTRUCTOR_FAILURE = `${EDIT_INSTRUCTOR}_FAILURE`;

//BaseApi
export const BaseApi = "http://localhost:5000";

// export const GET_INSTRUCTORS = "GET_INSTRUCTORS";
